# Numpy 튜토리얼 (1) - 배포용

<span style="color:red">
    본 자료는 교재 "파이썬으로 배우는 머신러닝의 교과서" chapter 2의 내용과 Stanford 강의 "CS231n, Python Numpy Tutorial"의 한글버전(http://aikorea.org/cs231n/python-numpy-tutorial/)을 파이썬 3 버전에 맞게 수정한 것과, TAEWAN.KIM 블로그 자료 "파이썬 데이터 사이언스 Cheat Sheet: NumPy 기초, 기본", http://taewan.kim/post/numpy_cheat_sheet/, 및 그 외에 다른 참고자료들을 일부 추가하여 만들었습니다.
</span>

참고 자료: 
- 이토마코토/박광수, 파이썬으로 배우는 머신러닝의 교과서, chapter 2, 한빛미디어, 2018
- Stanford university, CS231n, Python Numpy Tutorial,의 한글버전 (http://aikorea.org/cs231n/python-numpy-tutorial/)
- TAEWAN.KIM, 파이썬 데이터 사이언스 Cheat Sheet: NumPy 기초, 기본, http://taewan.kim/post/numpy_cheat_sheet/
- Numpy manual https://docs.scipy.org/doc/numpy/contents.html

**리스트로 벡터행렬 연산을 하는 경우의 문제점**:

In [1]:
[1,2] + [3,4]    # 1차원 리스트에서의 +는 벡터 덧셈이 아니라 list concatenation이 됨

[1, 2, 3, 4]

In [2]:
[[1,2], [3,4]] + [[5,6], [7,8]]    # 2차원 리스트(리스트의 리스트)에서도 마찬가지로 list concatenation이 일어남.

[[1, 2], [3, 4], [5, 6], [7, 8]]

Numpy는 파이썬이 벡터, 행렬 등으로 계산과학분야에 이용될때 핵심 역할을 하는 라이브러리입니다. Numpy는 고성능의 다차원 배열 객체와 이를 다룰 도구를 제공합니다.

## 배열

Numpy 배열은 동일한 자료형을 가지는 값들이 격자판 형태로 있는 것입니다. 각각의 값들은 튜플 형태로 색인 됩니다. rank는 배열이 몇 차원인지를 의미합니다; shape는 는 각 차원의 크기를 알려주는 정수들이 모인 튜플입니다.

파이썬의 리스트를 중첩해 Numpy 배열을 초기화 할 수 있고, 대괄호를 통해 각 요소에 접근할 수 있습니다:

In [3]:
import numpy as np    # 파이썬에서 NumPy를 사용할 때, numpy 모듈을 “np”로 임포트하여 사용합니다.

a = np.array([1, 2, 3])    # rank가 1인 배열 생성
print (a)
print (type(a))            # 출력 "<type 'numpy.ndarray'>"
print (a.ndim)             # a의 차원(rank): 출력 1
print (a.shape)            # 출력 "(3,)"
print (a[0], a[1], a[2])   # 출력 "1 2 3"
a[0] = 5                   # 요소를 변경
print (a)                  # 출력 "[5, 2, 3]"

b = np.array([[1,2,3],[4,5,6]])   # rank가 2인 배열 생성
print (b)
print (b.ndim)             # b의 차원(rank): 출력 2
print (b.shape)            # 출력 "(2, 3)"
w, h = b.shape
print ("w=",w,"h=",h)
print (b[0])               # 출력 "[1 2 3]""
print (b[0][0], b[0][1], b[1][0])   # 출력 "1 2 4"
print (b[0,0], b[0,1], b[1,0])   # 출력 "1 2 4"

[1 2 3]
<class 'numpy.ndarray'>
1
(3,)
1 2 3
[5 2 3]
[[1 2 3]
 [4 5 6]]
2
(2, 3)
w= 2 h= 3
[1 2 3]
1 2 4
1 2 4


**실습문제**: 1부터 9까지의 숫자를 가지는 3x3 행렬을 numpy 객체 A로 생성하여라. 
- A의 모든 원소를 출력하라.
- A의 차원(rank)를 출력하라.
- A의 shape를 출력하라.
- A의 모든 원소에 대해 첫번째 행은 10을 더하고, 두번째 행은 20을 더하고, 세번째 행은 30을 더한 뒤, A의 모든 원소를 출력하라.

In [4]:
import numpy as np
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(A)
print(A.ndim)
print(A.shape)
A[0,:]+=10
A[1,:]+=20
A[2,:]+=30
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
(3, 3)
[[11 12 13]
 [24 25 26]
 [37 38 39]]


**np.arange()에 관하여**

In [5]:
print(np.arange(10))      # 연속된 정수 벡터의 생성, cf) list형의 range(10) 

[0 1 2 3 4 5 6 7 8 9]


In [6]:
print(np.arange(5, 10))

[5 6 7 8 9]


In [7]:
print(np.arange(1, 10, 2))

[1 3 5 7 9]


In [8]:
j = np.array([4, 5, 6])
for i in np.arange(1,4):
    print(i)
    print(i + j)  # 1+[4, 5, 6] => [1, 1, 1]+[4, 5, 6] => [5, 6, 7] => broadcasting

1
[5 6 7]
2
[6 7 8]
3
[7 8 9]


리스트의 중첩이 아니더라도 Numpy는 배열을 만들기 위한 다양한 함수를 제공합니다.

In [9]:
import numpy as np

print (np.zeros(10))

a = np.zeros((2,2))  # 모든 값이 0인 배열 생성, 2차원 배열인 경우 튜플(2,2)로 차원을 나타냄, 따라서 안에 ()가 하나 더 있음
print (a)              # 출력 "[[ 0.  0.]
                     #       [ 0.  0.]]"
print (np.ones(10))

b = np.ones((1,2))   # 모든 값이 1인 배열 생성
print (b)              # 출력 "[[ 1.  1.]]"

c = np.full((2,2), 7) # 모든 값이 특정 상수인 배열 생성
print (c)               # 출력 "[[ 7.  7.]
                      #       [ 7.  7.]]"

d = np.eye(2)        # 2x2 단위행렬 생성
print (d)              # 출력 "[[ 1.  0.]
                     #       [ 0.  1.]]"
d = np.identity(2)   # np.eye(2)와 같은 결과
print (d) 

e = np.random.random((2,2)) # 임의의 값으로 채워진 배열 생성
print (e)                     # 임의의 값 출력 "[[ 0.91940167  0.08143941]
                            #                  [ 0.68744134  0.87236687]]"

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[[1. 1.]]
[[7 7]
 [7 7]]
[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]
[[0.83112209 0.46621549]
 [0.04552049 0.03985249]]


In [10]:
A=np.ones(5)
print(A.ndim)
A.shape

1


(5,)

In [11]:
A=np.ones((1,5))
print(A.ndim)
A.shape

2


(1, 5)

**실습문제**: 5x5 행렬을 하나 생성하여 모든 행을 0부터 4까지의 정수로 채우시오.

In [12]:
mat=np.zeros((5,5))
for i in np.arange(5):
    mat[i,:]=np.arange(5)  # mat[i,:] += [0, 1, 2, 3, 4] => [0, 0, 0, 0, 0] + [0, 1, 2, 3, 4]
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [13]:
mat=np.zeros((5,5))
for i in range(5):
    mat[i,:]=range(5)
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


In [14]:
mat=np.zeros((5,5))
mat+=np.arange(5)  # broadcasting 이용
print(mat)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


**실습문제**: 대각요소(diagonal element) 위는 1로 채우고, 아래는 0으로 채운 삼각행렬(triangular matrix)를 만드시오. (슬라이싱 기능을 사용하지 말고 for loop을 이용하시오.)

In [15]:
n=int(input("행렬의 크기 입력: "))
mm=np.ones((n,n))
for i in range(1,n):
    for j in range(i):  # 슬라이싱 이용 : mm[i,:i]
        mm[i,j]=0
print(mm)

행렬의 크기 입력: 10
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**실습문제**: 1부터 n^2까지의 숫자를 가지는 nxn 행렬을 numpy 객체 A로 생성하여라. 
- A의 모든 원소에 대해 첫번째 행은 10을 더하고, 두번째 행은 20을 더하고, 세번째 행은 30을 더하고, ..., 그런 후 A의 모든 원소를 출력하라.

In [16]:
n=int(input("행렬의 크기 입력: "))
A=np.zeros((n,n))
for i in range(n):
    for j in range(n):
        A[i,j]=i*n+j+1
        
for i in range(n):
    for j in range(n):
        A[i,j]+=10*(i+1)
print(A)

행렬의 크기 입력: 9
[[ 11.  12.  13.  14.  15.  16.  17.  18.  19.]
 [ 30.  31.  32.  33.  34.  35.  36.  37.  38.]
 [ 49.  50.  51.  52.  53.  54.  55.  56.  57.]
 [ 68.  69.  70.  71.  72.  73.  74.  75.  76.]
 [ 87.  88.  89.  90.  91.  92.  93.  94.  95.]
 [106. 107. 108. 109. 110. 111. 112. 113. 114.]
 [125. 126. 127. 128. 129. 130. 131. 132. 133.]
 [144. 145. 146. 147. 148. 149. 150. 151. 152.]
 [163. 164. 165. 166. 167. 168. 169. 170. 171.]]


# 요소가 랜덤인 배열의 생성

In [17]:
np.random.rand(2, 3)      # (2,3) 행렬의 요소를 0과 1사이의 균등분포로 랜덤하게 생성

array([[0.30013189, 0.39443245, 0.04651369],
       [0.36109509, 0.19877945, 0.27286638]])

In [18]:
np.random.randn(2, 3)      # (2,3) 행렬의 요소를 평균 0, 분산 1의 가우스분포로 랜덤하게 생성

array([[ 0.18022371, -1.07736949,  0.54067354],
       [-0.60589437, -0.0570487 , -2.65544664]])

In [19]:
np.random.randint(10, 100, 5)      # 10부터 100까지 정수 5개를 랜덤하게 생성

array([38, 75, 11, 66, 77])

In [20]:
np.random.randint(10, 100, (2,5))      # 10부터 100까지 정수를 (2,5) 행렬로 랜덤하게 생성

array([[35, 39, 84, 61, 91],
       [20, 44, 11, 90, 19]])

**실습문제**: 원소들의 값이 랜덤인 10x10 행렬을 생성하고, 최대값과 최소값을 찾으시오. (np.max()와 np.min() 함수를 사용하지 말고 for loop을 이용하시오.)

In [21]:
hh=np.random.rand(10,10).round(3)
print(hh)
min=hh[0,0]
max=hh[0,0]
for i in range(10):
    for j in range(10):
        if hh[i,j]>max:
            max=hh[i,j]
            max_index=(i,j)
        elif hh[i,j]<min:
            min=hh[i,j]
            min_index=(i,j)
print("최댓값:",max,"\t인덱스:",max_index,"\n최솟값:",min,"\t인덱스:",min_index)

[[0.734 0.557 0.68  0.607 0.285 0.09  0.633 0.385 0.098 0.192]
 [0.23  0.869 0.262 0.501 0.213 0.316 0.255 0.656 0.724 0.17 ]
 [0.892 0.614 0.564 0.497 0.259 0.897 0.258 0.809 0.474 0.219]
 [0.259 0.712 0.287 0.525 0.761 0.653 0.222 0.75  0.259 0.175]
 [0.444 0.283 0.725 0.535 0.103 0.637 0.166 0.325 0.437 0.61 ]
 [0.605 0.06  0.913 0.262 0.62  0.582 0.231 0.188 0.671 0.02 ]
 [0.389 0.741 0.749 0.688 0.785 0.521 0.726 0.208 0.557 0.075]
 [0.05  0.563 0.863 0.531 0.019 0.454 0.264 0.215 0.399 0.197]
 [0.773 0.629 0.969 0.799 0.577 0.396 0.636 0.254 0.162 0.731]
 [0.215 0.079 0.878 0.949 0.507 0.317 0.745 0.795 0.154 0.755]]
최댓값: 0.969 	인덱스: (8, 2) 
최솟값: 0.019 	인덱스: (7, 4)


**random number 생성 시 seed 값 주기**: 

    np.random.seed(seed_value)

In [22]:
A = np.ones((10,10))
A.shape[0]

10

In [23]:
# seed 값을 설정하여 아래에서 난수가 재연 가능하도록 함
np.random.seed(100)

In [24]:
np.random.rand(2, 3)

array([[0.54340494, 0.27836939, 0.42451759],
       [0.84477613, 0.00471886, 0.12156912]])

In [25]:
np.random.randn(2, 3)

array([[ 0.98132079,  0.51421884,  0.22117967],
       [-1.07004333, -0.18949583,  0.25500144]])

In [26]:
np.random.randint(10, 100, 5)

array([26, 19, 96, 12, 37])

## 자료형

NumPy는 다음과 같은 데이터 타입을 지원합니다. 배열을 생성할 때 dtype속성으로 다음과 같은 데이터 타입을 지정할 수 있습니다:
- np.int32 : 32 비트 정수 타입
- np.float64 : 64 비트 부동 소수 타입
- np.complex : 복소수 (128 float)
- np.bool : 불린 타입 (True, False)
- np.object : 파이썬 객체 타입
- np.string_ : 고정자리 스트링 타입
- np.unicode_ : 고정자리 유니코드 타입


Numpy는 배열이 생성될 때 자료형을 스스로 추측합니다, 그러나 배열을 생성할 때 명시적으로 특정 자료형을 지정할 수도 있습니다. 

In [27]:
import numpy as np

x = np.array([1, 2])  # Numpy가 자료형을 추측해서 선택
print (x.dtype)         # 출력 "int32"

x = np.array([1.0, 2.0])  # Numpy가 자료형을 추측해서 선택
print (x.dtype)             # 출력 "float64"

x = np.array([1, 2], dtype=np.int64)  # 특정 자료형을 명시적으로 지정
print (x.dtype)                         # 출력 "int64"

int32
float64
int64


## 배열의 속성 확인

![대체 텍스트](attribute.JPG)

In [28]:
#데모 배열 객체 생성
arr = np.random.random((5,2,3))
arr

array([[[0.95018431, 0.12665424, 0.07898787],
        [0.31135313, 0.63238359, 0.69935892]],

       [[0.64196495, 0.92002378, 0.29887635],
        [0.56874553, 0.17862432, 0.5325737 ]],

       [[0.64669147, 0.14206538, 0.58138896],
        [0.47918994, 0.38641911, 0.44046495]],

       [[0.40475733, 0.44225404, 0.03012328],
        [0.77600531, 0.55095838, 0.3810734 ]],

       [[0.52926578, 0.9568769 , 0.17582131],
        [0.11830284, 0.86294567, 0.07486688]]])

In [29]:
#배열 타입 조회
type(arr)

numpy.ndarray

In [30]:
# 배열의 차원 수 
arr.ndim

3

In [31]:
# 배열의 shape 확인
arr.shape

(5, 2, 3)

In [32]:
# 배열의 길이: shape(k, m, n) ==> k
len(arr)

5

In [33]:
# 배열의 요소 수: shape(k, m, n) ==> k*m*n
arr.size

30

In [34]:
# 배열 타입 확인
arr.dtype

dtype('float64')

In [35]:
# 배열 요소를 int로 변환
# 요소의 실제 값이 변환되는 것이 아님
# View의 출력 타입과 연산을 변환하는 것
arr.astype(np.int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [36]:
np.int32(arr)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [37]:
# np.float으로 타입을 다시 변환하면 np.int 변환 이전 값으로 모든 원소 값이 복원됨
arr.astype(np.float)

array([[[0.95018431, 0.12665424, 0.07898787],
        [0.31135313, 0.63238359, 0.69935892]],

       [[0.64196495, 0.92002378, 0.29887635],
        [0.56874553, 0.17862432, 0.5325737 ]],

       [[0.64669147, 0.14206538, 0.58138896],
        [0.47918994, 0.38641911, 0.44046495]],

       [[0.40475733, 0.44225404, 0.03012328],
        [0.77600531, 0.55095838, 0.3810734 ]],

       [[0.52926578, 0.9568769 , 0.17582131],
        [0.11830284, 0.86294567, 0.07486688]]])

In [38]:
np.float64(arr)

array([[[0.95018431, 0.12665424, 0.07898787],
        [0.31135313, 0.63238359, 0.69935892]],

       [[0.64196495, 0.92002378, 0.29887635],
        [0.56874553, 0.17862432, 0.5325737 ]],

       [[0.64669147, 0.14206538, 0.58138896],
        [0.47918994, 0.38641911, 0.44046495]],

       [[0.40475733, 0.44225404, 0.03012328],
        [0.77600531, 0.55095838, 0.3810734 ]],

       [[0.52926578, 0.9568769 , 0.17582131],
        [0.11830284, 0.86294567, 0.07486688]]])

## 배열 인덱싱

Numpy는 배열을 인덱싱하는 몇 가지 방법을 제공합니다.

**슬라이싱:** 파이썬 리스트와 유사하게, Numpy 배열도 슬라이싱이 가능합니다. Numpy 배열은 다차원인 경우가 많기에, 각 차원별로 어떻게 슬라이스할건지 명확히 해야 합니다:

In [39]:
import numpy as np

# Create the following rank 2 array with shape (3, 4)
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 슬라이싱을 이용하여 첫 두 행과 1열, 2열로 이루어진 부분배열을 만들어 봅시다;
# b는 shape가 (2,2)인 배열이 됩니다:
# [[2 3]
#  [6 7]]
b = a[:2, 1:3]
print (b)

# 슬라이싱된 배열은 원본 배열과 같은 데이터를 참조합니다, 즉 슬라이싱된 배열을 수정하면
# 원본 배열 역시 수정됩니다.
print (a[0, 1])   # 출력 "2"
b[0, 0] = 77    # b[0, 0]은 a[0, 1]과 같은 데이터입니다
print (a[0, 1])   # 출력 "77"

[[2 3]
 [6 7]]
2
77


정수를 이용한 인덱싱과 슬라이싱을 혼합하여 사용할 수 있습니다. 하지만 이렇게 할 경우, 기존의 배열보다 낮은 rank의 배열이 얻어집니다.

In [40]:
import numpy as np

# 아래와 같은 요소를 가지는 rank가 2이고 shape가 (3, 4)인 배열 생성
# [[ 1  2  3  4]
#  [ 5  6  7  8]
#  [ 9 10 11 12]]
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

# 배열의 중간 행에 접근하는 두 가지 방법이 있습니다.
# 정수 인덱싱과 슬라이싱을 혼합해서 사용하면 낮은 rank의 배열이 생성되지만,
# 슬라이싱만 사용하면 원본 배열과 동일한 rank의 배열이 생성됩니다.
row_r1 = a[1, :]    # 배열a의 두 번째 행을 rank가 1인 배열로
row_r2 = a[1:2, :]  # 배열a의 두 번째 행을 rank가 2인 배열로
print (row_r1, row_r1.shape)  # 출력 "[5 6 7 8] (4,)"
print (row_r2, row_r2.shape)  # 출력 "[[5 6 7 8]] (1, 4)"

# 행이 아닌 열의 경우에도 마찬가지입니다:
col_r1 = (a[:, 1])
col_r2 = (a[:, 1:2])
print (col_r1, col_r1.shape)  # 출력 "[ 2  6 10] (3,)"
print (col_r2, col_r2.shape)  # 출력 "[[ 2]
                            #       [ 6]
                            #       [10]] (3, 1)"

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**실습문제**: 경계선(border)의 원소는 모두 1이고, 내부 원소는 모두 0인 (10,10) 행렬을 생성하시오.

In [41]:
brdr=np.ones((10,10))
brdr[1:-1,1:-1]=0
print(brdr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**실습문제**: 대각요소(diagonal element) 위는 1로 채우고, 아래는 0으로 채운 삼각행렬(triangular matrix)를 만드시오. (슬라이싱 기능을 사용하시오.)

In [42]:
tr=np.zeros((10,10))
for i in range(10):
    tr[i,i:]=1
print(tr)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 1. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 1. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 1. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 1. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 1. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


**실습문제**: 8x8 행렬을 생성해서 체커보드(checkerboard) 패턴으로 0과 1로 초기화 하시오. (예를들어 아래는 4x4 행렬의 체커보드 패턴이다.)

    1 0 1 0
    0 1 0 1
    1 0 1 0
    0 1 0 1

In [43]:
hhh=np.zeros((8,8))
for i in range(8):
    if i%2==0:
        hhh[i][::2]=1
    else:
        hhh[i][1::2]=1
print(hhh)

[[1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]]


**불리언 배열 인덱싱:** 불리언 배열 인덱싱을 통해 배열 속 요소를 취사선택할 수 있습니다. 불리언 배열 인덱싱은 특정 조건을 만족하게 하는 요소만 선택하고자 할 때 자주 사용됩니다.

In [44]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])

bool_idx = (a > 2)  # 2보다 큰 a의 요소를 찾습니다;
                    # 이 코드는 a와 shape가 같고 불리언 자료형을 요소로 하는 numpy 배열을 반환합니다,
                    # bool_idx의 각 요소는 동일한 위치에 있는 a의
                    # 요소가 2보다 큰지를 말해줍니다.

print (bool_idx)      # 출력 "[[False False]
                    #       [ True  True]
                    #       [ True  True]]"

# 불리언 배열 인덱싱을 통해 bool_idx에서
# 참 값을 가지는 요소로 구성되는
# rank 1인 배열을 구성할 수 있습니다.
print (a[bool_idx])  # 출력 "[3 4 5 6]"

# 위에서 한 모든것을 한 문장으로 할 수 있습니다:
print (a[a > 2])     # 출력 "[3 4 5 6]"

# 불리언 배열 인덱싱을 통해 요소를 수정하는 것도 가능합니다
a[a > 2] = 99
print (a)

[[False False]
 [ True  True]
 [ True  True]]
[3 4 5 6]
[3 4 5 6]
[[ 1  2]
 [99 99]
 [99 99]]


**실습문제**: 1부터 10까지의 정수로 구성된 1차원 배열을 생성한 뒤 2과 3의 배수를 음수로 만드시오.

In [45]:
aa=np.arange(1,11)
aa[(aa%2==0)|(aa%3==0)]*=-1
print(aa)

[  1  -2  -3  -4   5  -6   7  -8  -9 -10]


## 배열의 형태 변경

In [46]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


위의 배열을 2*5의 행렬로 변경하려면 np.reshape() 함수를 사용하여 다음과 같이 입력합니다.

In [47]:
a.reshape(2, 5)      # 2*5의 행렬로 변환

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [48]:
a.reshape(2, -1)      # 행렬의 마지막 차수를 -1로 하면 시스템에서 알아서 5로 계산함

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

np.reshape() 함수를 사용하여 행렬을 벡터로도 변환할 수 있다. 

In [49]:
a = np.array([[1,2,3], [4,5,6]])
np.reshape(a, 6)    # 행렬을 벡터로 변환도 가능

array([1, 2, 3, 4, 5, 6])

In [50]:
np.reshape(a, -1)   # 벡터의 원소의 개수를 -1로 하면 시스템에서 알아서 6으로 계산함

array([1, 2, 3, 4, 5, 6])